#!/usr/bin/env python
# -*- coding: utf-8 -*-
point_choices = {
1 : 'Kościelec (szczyt)',
2 : 'Wyżnia Kondracka Przełęcz',
3 : 'Smocza Jama (jaskinia)',
4 : 'Rówień Waksmundzka',
5 : 'Kiry',
6 : 'Dolina Jarząbcza',
7 : 'Wołowiec (szczyt)',
8 : 'Żadni Granat (szczyt)',
9 : 'Myślenickie Turnie',
10 : 'Rzeżuchy, Dolina Roztoki',
11 : 'Przełęcz pod Kondracką Kopą',
12 : 'Kuźnice',
13 : 'Nędzówka',
14 : 'Toporowa Cyrhla',
15 : 'Gęsia Szyja (szczyt)',
16 : 'Siwa Przełęcz',
17 : 'Siklawica (wodospad)',
18 : 'Dolina za Mnichem',
19 : 'Rysy (szczyt)',
20 : 'PTTK Murowaniec na Hali Gąsienicowej',
21 : 'Las Brzanówka',
22 : 'Polana pod Wołoszynem',
23 : 'PTTK w Morskim Oku',
24 : 'Dolina za Bramką',
25 : 'Dolina Lejowa',
26 : 'Szpiglasowy Wierch (szczyt)',
27 : 'Wyżnia Pisana Polana',
28 : 'Ornak (szczyt)',
29 : 'Wielki Kopiec (szczyt)',
30 : 'Kondracka Kopa (szczyt)',
31 : 'Jarząbczy Wierch (szczyt)',
32 : 'Rusinowa Polana',
33 : 'Przełęcz między Kopami',
34 : 'Dolina Białego',
35 : 'Sarnia Skała (szczyt)',
36 : 'PTTK w Kalatówkach',
37 : 'Polana Chochołowska',
38 : 'Jaszcurówka 2',
39 : 'Cudakowa Polana',
40 : 'Polana Strążyska',
41 : 'Wielka Polana',
42 : 'Wodogrzmoty Mickiewicza',
43 : 'Małołączniak (szczyt)',
44 : 'Siwy Zwrotnik',
45 : 'Pyszniańska Przełęcz',
46 : 'PTTK na Hali Kondratowej',
47 : 'Dolina Strążyska',
48 : 'Olczysta Polana',
49 : 'Rakoń (szczyt)',
50 : 'Palenica Białczańska',
51 : 'PTTK w Dolinie Pięciu Stawów',
52 : 'Szpiglasowa Przełęcz',
53 : 'Smreczyński Staw',
54 : 'Kasprowy Wierch (szczyt)',
55 : 'Świnica (szczyt)',
56 : 'Przełęcz Krzyżne',
57 : 'Siklawa (wodospad)',
58 : 'PTTK w Dolinie Roztoki',
59 : 'Przełęcz w Grzybowcu',
60 : 'Przełęcz Kondracka',
61 : 'Iwanicka Przełęcz',
62 : 'Wrota Chałubińskiego',
63 : 'Polana Białego',
64 : 'Leśniczówka Chochołowska',
65 : 'Kozi Wierch (szczyt)',
66 : 'Psia Trawka',
67 : 'Przełęcz pod Chłopkiem',
68 : 'Liliowe',
69 : 'Zamarzły Staw, rozwidlenie z szlakiem Żółtym',
70 : 'Leśniczówka w Brzezinach',
71 : 'Szałasiska',
72 : 'Świnicka Przełęcz',
73 : 'Niżnia Kominiarska Polana',
74 : 'Polana na Stołach',
75 : 'Giewont (szczyt)',
76 : 'Trzydniowiański Wierch (szczyt)',
77 : 'Czarny Staw Gąsienicowy przy szlaku żółtym',
78 : 'Skrajny Granat (szczyt)',
79 : 'Dolina Pańszczyca przy zielonym szlaku',
80 : 'Ciemniak (szczyt)',
81 : 'Przysłop Miętusi',
82 : 'Wyżnia Dolina Chochołowska',
83 : 'Zamarzły Staw, rozwidlenie z szlakiem Niebieskim',
84 : 'Rapasiowa Turnia',
85 : 'Dolina Pańszczyca przy żółtym szlaku',
86 : 'Przełęcz nad Buczynową Dolinką',
87 : 'Przełęcz Czerwona',
88 : 'Dziura (jaskinia)',
89 : 'Starobociański Wierch (szczyt)',
90 : 'PTTK na Polanie Ornaczańskiej',
91 : 'Niżnie Solnisko',
92 : 'Zawrat',
93 : 'Droga pod Reglami',
94 : 'Błyszcz (szczyt)',
95 : 'Niżni Zagon',
96 : 'Polana Trzydniówka',
97 : 'Dolina Małej Łąki',
98 : 'Brama Kraszewskiego',
99 : 'Czarny Staw',
100 : 'Kazalnica (szczyt)',
101 : 'Zielony Staw',
102 : 'Parking Kuźnice',
103 : 'Chuda Przełęcz',
104 : 'Między Ściany',
105 : 'Parking przy Wierchu Poroniec',
106 : 'Kozia Przełęcz',
107 : 'Jaskinia Mylna (jaskinia)',
108 : 'Karb',
109 : 'Grześ (szczyt)',
110 : 'Czarny Staw Gąsienicowy przy szlaku niebieskim',
111 : 'Kończysty Wierch (szczyt)',
112 : 'Nosalowa Przełęcz',
}


