#!/usr/bin/env python
# -*- coding: utf-8 -*-
from Vertex import Vertex
from Graph import Graph

tatry_easy = Graph()

palenica = Vertex('Palenica Białczańska')
palenica.start = True
wodogrzmoty = Vertex('Wodogrzmoty Mickiewicza')
pttk_Roztoki = Vertex('PTTK w Dolinie Roztoki')
pttk_Roztoki.target = True
pttk_Morskie = Vertex('PTTK w Morskim Oku')
pttk_Morskie.target = True
czarny_staw = Vertex('Czarny Staw')
czarny_staw.target = True
rysy = Vertex('Rysy (szczyt)')
rysy.target = True
rzezuchy = Vertex('Rzeżuchy, Dolina Roztoki')
pttk_5stawow = Vertex('PTTK w Dolinie Pięciu Stawów')
pttk_5stawow.target = True
siklawa = Vertex('Siklawa (wodospad)')
siklawa.target = True
nizni_zagon = Vertex('Niżni Zagon')
dolina_za_mnichem = Vertex('Dolina za Mnichem')
wrota_chalubinskiego = Vertex('Wrota Chałubińskiego')
wrota_chalubinskiego.target = True
kazalnica = Vertex('Kazalnica (szczyt)')
kazalnica.target = True
przel_pod_chlopkiem = Vertex('Przełęcz pod Chłopkiem')
przel_pod_chlopkiem.target = True
szpiglasowa_przel = Vertex('Szpiglasowa Przełęcz')
szpiglasowy_wierch = Vertex('Szpiglasowy Wierch (szczyt)')
szpiglasowy_wierch.target = True
niznie_solnisko = Vertex('Niżnie Solnisko')
przel_krzyzne = Vertex('Przełęcz Krzyżne')
kozi_wierch = Vertex('Kozi Wierch (szczyt)')
kozi_wierch.target = True
kozia_przel = Vertex('Kozia Przełęcz')
zawrat = Vertex('Zawrat')
zawrat.target = True
przel_nad_buczy = Vertex('Przełęcz nad Buczynową Dolinką')
zadni_granat = Vertex('Żadni Granat (szczyt)')
zadni_granat.target = True
skrajny_granat = Vertex('Skrajny Granat (szczyt)')
skrajny_granat.target = True
zamarzly_staw_z = Vertex('Zamarzły Staw, rozwidlenie z szlakiem Żółtym')
zamarzly_staw_n = Vertex('Zamarzły Staw, rozwidlenie z szlakiem Niebieskim')
pol_pod_woloszynem = Vertex('Polana pod Wołoszynem')
rowien_waksmundzka = Vertex('Rówień Waksmundzka')
gesia_szyja = Vertex('Gęsia Szyja (szczyt)')
gesia_szyja.target = True
rusinowa_pol = Vertex('Rusinowa Polana')
rusinowa_pol.target = True
droga_oswalda = Vertex('Parking przy Wierchu Poroniec')
droga_oswalda.start = True
las_brzanowka = Vertex('Las Brzanówka')
las_brzanowka.start = True
jaszczurowka = Vertex('Toporowa Cyrhla')
jaszczurowka.start = True
psia_trawka = Vertex('Psia Trawka')
brzeziny_les = Vertex('Leśniczówka w Brzezinach')
brzeziny_les.start = True
pttk_hala_gasienicowa = Vertex('PTTK Murowaniec na Hali Gąsienicowej')
pttk_hala_gasienicowa.target = True
dolina_pan_z = Vertex('Dolina Pańszczyca przy żółtym szlaku')
dolina_pan_ziel = Vertex('Dolina Pańszczyca przy zielonym szlaku')
wielki_kopiec = Vertex('Wielki Kopiec (szczyt)')
wielki_kopiec.target = True
olczysta_pol = Vertex('Olczysta Polana')
jaszczurowka_2 = Vertex('Jaszcurówka 2')
jaszczurowka_2.start = True
nosalowa_przel = Vertex('Nosalowa Przełęcz')
nosalowa_przel.target = True
parking_kuznice = Vertex('Parking Kuźnice')
parking_kuznice.start = True
kuznice = Vertex('Kuźnice')
przel_miedzy_kopami = Vertex('Przełęcz między Kopami')
czarny_staw_gasienicowy_z = Vertex('Czarny Staw Gąsienicowy przy szlaku żółtym')
czarny_staw_gasienicowy_n = Vertex('Czarny Staw Gąsienicowy przy szlaku niebieskim')
czarny_staw_gasienicowy_n.target = True
karb = Vertex('Karb')
koscielec = Vertex('Kościelec (szczyt)')
koscielec.target = True
zielony_staw = Vertex('Zielony Staw')
swinicka_przel = Vertex('Świnicka Przełęcz')
szalasiska = Vertex('Szałasiska')
liliowe = Vertex('Liliowe')
kasprowy = Vertex('Kasprowy Wierch (szczyt)')
myslenickie_turnie = Vertex('Myślenickie Turnie')
pttk_kalatowki = Vertex('PTTK w Kalatówkach')
pttk_kalatowki.target = True
pttk_hala_kondratowa = Vertex('PTTK na Hali Kondratowej')
pttk_hala_kondratowa.target = True
swinica = Vertex('Świnica (szczyt)')
swinica.target = True
przel_pod_kond = Vertex('Przełęcz pod Kondracką Kopą')
przel_kond = Vertex('Przełęcz Kondracka')
wyznia_przel_kond = Vertex('Wyżnia Kondracka Przełęcz')
giewont = Vertex('Giewont (szczyt)')
giewont.target = True
kondracka = Vertex('Kondracka Kopa (szczyt)')
kondracka.target = True
polana_bialego = Vertex('Polana Białego')
polana_bialego.target = True
czerwona_przel = Vertex('Przełęcz Czerwona')
sarnia = Vertex('Sarnia Skała (szczyt)')
sarnia.target = True
polana_strazyska = Vertex('Polana Strążyska')
polana_strazyska.target = True
dolina_stazyska = Vertex('Dolina Strążyska')
dolina_stazyska.start = True
droga_pod_reglami = Vertex('Droga pod Reglami')
dziura = Vertex('Dziura (jaskinia)')
dziura.target = True
siklawica = Vertex('Siklawica (wodospad)')
siklawica.target = True
przel_w_grzyb = Vertex('Przełęcz w Grzybowcu')
dolina_za_bram = Vertex('Dolina za Bramką')
dolina_za_bram.target = True
dolina_malej = Vertex('Dolina Małej Łąki')
dolina_malej.start = True
rapasiowa_turnia = Vertex('Rapasiowa Turnia')
wielka_polana = Vertex('Wielka Polana')
wielka_polana.target = True
malolaczniak = Vertex('Małołączniak (szczyt)')
malolaczniak.target = True
ciemniak = Vertex('Ciemniak (szczyt)')
ciemniak.target = True
przyslop_miet = Vertex('Przysłop Miętusi')
nedzowka = Vertex('Nędzówka')
nedzowka.start = True
kiry = Vertex('Kiry')
kiry.start = True
cudakowa_pol = Vertex('Cudakowa Polana')
cudakowa_pol.target = True
chuda_przel = Vertex('Chuda Przełęcz')
pttk_ornaczanska = Vertex('PTTK na Polanie Ornaczańskiej')
pttk_ornaczanska.target = True
wyznia_pisana = Vertex('Wyżnia Pisana Polana')
smocza = Vertex('Smocza Jama (jaskinia)')
smocza.target = True
mylna = Vertex('Jaskinia Mylna (jaskinia)')
mylna.target = True
brama_krasz = Vertex('Brama Kraszewskiego')
polana_na_stolach = Vertex('Polana na Stołach')
polana_na_stolach.target = True
smreczynski_staw = Vertex('Smreczyński Staw')
smreczynski_staw.target = True
dolina_lejowa = Vertex('Dolina Lejowa')
dolina_lejowa.start = True
niznia_kominiarska = Vertex('Niżnia Kominiarska Polana')
niznia_kominiarska.target = True
miedzy_sciany = Vertex('Między Ściany')
lesniczowka_chocho = Vertex('Leśniczówka Chochołowska')
iwanicka_przel = Vertex('Iwanicka Przełęcz')
ornak = Vertex('Ornak (szczyt)')
ornak.target = True
siwa_przel = Vertex('Siwa Przełęcz')
siwy_zwrotnik = Vertex('Siwy Zwrotnik')
blyszcz = Vertex('Błyszcz (szczyt)')
blyszcz.target = True
pysznianska_przel = Vertex('Pyszniańska Przełęcz')
starobocianski = Vertex('Starobociański Wierch (szczyt)')
starobocianski.target = True
konczysty = Vertex('Kończysty Wierch (szczyt)')
konczysty.target = True
dolina_bialego = Vertex('Dolina Białego')
dolina_bialego.start = True
polana_trzydniowka = Vertex('Polana Trzydniówka')
trzydniowianski = Vertex('Trzydniowiański Wierch (szczyt)')
trzydniowianski.target = True
dolina_jarzabcza = Vertex('Dolina Jarząbcza')
dolina_jarzabcza.target = True
chocholowska = Vertex('Polana Chochołowska')
chocholowska.target = True
grzes = Vertex('Grześ (szczyt)')
grzes.target = True
rakon = Vertex('Rakoń (szczyt)')
wolowiec = Vertex('Wołowiec (szczyt)')
wolowiec.target = True
jarzabczy_wierch = Vertex('Jarząbczy Wierch (szczyt)')
jarzabczy_wierch.target = True
dolina_wyznia = Vertex('Wyżnia Dolina Chochołowska')

tatry_easy.add_vertex(palenica)
tatry_easy.add_vertex(wodogrzmoty)
tatry_easy.add_vertex(pttk_Roztoki)
tatry_easy.add_vertex(pttk_Morskie)
tatry_easy.add_vertex(czarny_staw)
tatry_easy.add_vertex(rysy)
tatry_easy.add_vertex(rzezuchy)
tatry_easy.add_vertex(pttk_5stawow)
tatry_easy.add_vertex(siklawa)
tatry_easy.add_vertex(nizni_zagon)
tatry_easy.add_vertex(dolina_za_mnichem)
tatry_easy.add_vertex(wrota_chalubinskiego)
tatry_easy.add_vertex(kazalnica)
tatry_easy.add_vertex(przel_pod_chlopkiem)
tatry_easy.add_vertex(szpiglasowa_przel)
tatry_easy.add_vertex(szpiglasowy_wierch)
tatry_easy.add_vertex(niznie_solnisko)
tatry_easy.add_vertex(przel_krzyzne)
tatry_easy.add_vertex(kozi_wierch)
tatry_easy.add_vertex(kozia_przel)
tatry_easy.add_vertex(zawrat)
tatry_easy.add_vertex(przel_nad_buczy)
tatry_easy.add_vertex(zadni_granat)
tatry_easy.add_vertex(skrajny_granat)
tatry_easy.add_vertex(zamarzly_staw_z)
tatry_easy.add_vertex(zamarzly_staw_n)
tatry_easy.add_vertex(pol_pod_woloszynem)
tatry_easy.add_vertex(rowien_waksmundzka)
tatry_easy.add_vertex(gesia_szyja)
tatry_easy.add_vertex(rusinowa_pol)
tatry_easy.add_vertex(droga_oswalda)
tatry_easy.add_vertex(las_brzanowka)
tatry_easy.add_vertex(jaszczurowka)
tatry_easy.add_vertex(psia_trawka)
tatry_easy.add_vertex(brzeziny_les)
tatry_easy.add_vertex(pttk_hala_gasienicowa)
tatry_easy.add_vertex(dolina_pan_z)
tatry_easy.add_vertex(dolina_pan_ziel)
tatry_easy.add_vertex(wielki_kopiec)
tatry_easy.add_vertex(olczysta_pol)
tatry_easy.add_vertex(jaszczurowka_2)
tatry_easy.add_vertex(nosalowa_przel)
tatry_easy.add_vertex(parking_kuznice)
tatry_easy.add_vertex(kuznice)
tatry_easy.add_vertex(przel_miedzy_kopami)
tatry_easy.add_vertex(czarny_staw_gasienicowy_z)
tatry_easy.add_vertex(czarny_staw_gasienicowy_n)
tatry_easy.add_vertex(karb)
tatry_easy.add_vertex(koscielec)
tatry_easy.add_vertex(zielony_staw)
tatry_easy.add_vertex(swinicka_przel)
tatry_easy.add_vertex(szalasiska)
tatry_easy.add_vertex(liliowe)
tatry_easy.add_vertex(kasprowy)
tatry_easy.add_vertex(myslenickie_turnie)
tatry_easy.add_vertex(pttk_kalatowki)
tatry_easy.add_vertex(pttk_hala_kondratowa)
tatry_easy.add_vertex(swinica)
tatry_easy.add_vertex(przel_pod_kond)
tatry_easy.add_vertex(przel_kond)
tatry_easy.add_vertex(wyznia_przel_kond)
tatry_easy.add_vertex(giewont)
tatry_easy.add_vertex(kondracka)
tatry_easy.add_vertex(polana_bialego)
tatry_easy.add_vertex(czerwona_przel)
tatry_easy.add_vertex(sarnia)
tatry_easy.add_vertex(polana_strazyska)
tatry_easy.add_vertex(dolina_stazyska)
tatry_easy.add_vertex(droga_pod_reglami)
tatry_easy.add_vertex(dziura)
tatry_easy.add_vertex(siklawica)
tatry_easy.add_vertex(przel_w_grzyb)
tatry_easy.add_vertex(dolina_za_bram)
tatry_easy.add_vertex(dolina_malej)
tatry_easy.add_vertex(rapasiowa_turnia)
tatry_easy.add_vertex(wielka_polana)
tatry_easy.add_vertex(malolaczniak)
tatry_easy.add_vertex(ciemniak)
tatry_easy.add_vertex(przyslop_miet)
tatry_easy.add_vertex(nedzowka)
tatry_easy.add_vertex(kiry)
tatry_easy.add_vertex(cudakowa_pol)
tatry_easy.add_vertex(chuda_przel)
tatry_easy.add_vertex(pttk_ornaczanska)
tatry_easy.add_vertex(wyznia_pisana)
tatry_easy.add_vertex(smocza)
tatry_easy.add_vertex(mylna)
tatry_easy.add_vertex(brama_krasz)
tatry_easy.add_vertex(polana_na_stolach)
tatry_easy.add_vertex(smreczynski_staw)
tatry_easy.add_vertex(dolina_lejowa)
tatry_easy.add_vertex(niznia_kominiarska)
tatry_easy.add_vertex(miedzy_sciany)
tatry_easy.add_vertex(lesniczowka_chocho)
tatry_easy.add_vertex(iwanicka_przel)
tatry_easy.add_vertex(ornak)
tatry_easy.add_vertex(siwa_przel)
tatry_easy.add_vertex(siwy_zwrotnik)
tatry_easy.add_vertex(blyszcz)
tatry_easy.add_vertex(pysznianska_przel)
tatry_easy.add_vertex(starobocianski)
tatry_easy.add_vertex(konczysty)
tatry_easy.add_vertex(dolina_bialego)
tatry_easy.add_vertex(polana_trzydniowka)
tatry_easy.add_vertex(trzydniowianski)
tatry_easy.add_vertex(dolina_jarzabcza)
tatry_easy.add_vertex(chocholowska)
tatry_easy.add_vertex(grzes)
tatry_easy.add_vertex(rakon)
tatry_easy.add_vertex(wolowiec)
tatry_easy.add_vertex(jarzabczy_wierch)
tatry_easy.add_vertex(dolina_wyznia)

tatry_easy.add_edge(palenica, wodogrzmoty, 40, 0)
tatry_easy.add_edge(wodogrzmoty, pttk_Roztoki, 15, 0)
tatry_easy.add_edge(palenica, rusinowa_pol, 40, 0)
tatry_easy.add_edge(rusinowa_pol, droga_oswalda, 60, 0)
tatry_easy.add_edge(rusinowa_pol, las_brzanowka, 75, 0)
tatry_easy.add_edge(rusinowa_pol, gesia_szyja, 30, 0)
tatry_easy.add_edge(palenica, pol_pod_woloszynem, 35, 0)
tatry_easy.add_edge(pol_pod_woloszynem, rowien_waksmundzka, 40, 0)
tatry_easy.add_edge(pol_pod_woloszynem, wodogrzmoty, 30, 0)
tatry_easy.add_edge(wodogrzmoty, pttk_Morskie, 90, 0)
tatry_easy.add_edge(wodogrzmoty, rzezuchy, 70, 0)
tatry_easy.add_edge(pttk_Morskie, czarny_staw, 50, 0)
tatry_easy.add_edge(pttk_Morskie, dolina_za_mnichem, 70, 0)
tatry_easy.add_edge(pttk_Morskie, pttk_5stawow, 110, 0)
tatry_easy.add_edge(dolina_za_mnichem, wrota_chalubinskiego, 60, 0)
tatry_easy.add_edge(niznie_solnisko, nizni_zagon, 10, 0)
tatry_easy.add_edge(nizni_zagon, pttk_5stawow, 10, 0)
tatry_easy.add_edge(nizni_zagon, siklawa, 5, 0)
tatry_easy.add_edge(nizni_zagon, przel_krzyzne, 80, 0)
tatry_easy.add_edge(pttk_5stawow, rzezuchy, 40, 0)
tatry_easy.add_edge(rzezuchy, siklawa, 40, 0)
tatry_easy.add_edge(rowien_waksmundzka, psia_trawka, 60, 0)
tatry_easy.add_edge(rowien_waksmundzka, dolina_pan_ziel, 70, 0)
tatry_easy.add_edge(rowien_waksmundzka, gesia_szyja, 30, 0)
tatry_easy.add_edge(psia_trawka, brzeziny_les, 45, 0)
tatry_easy.add_edge(psia_trawka, jaszczurowka, 70, 0)
tatry_easy.add_edge(psia_trawka, pttk_hala_gasienicowa, 90, 0)
tatry_easy.add_edge(dolina_pan_ziel, dolina_pan_z, 30, 0)
tatry_easy.add_edge(dolina_pan_ziel, pttk_hala_gasienicowa, 75, 0)
tatry_easy.add_edge(dolina_pan_z, pttk_hala_gasienicowa, 60, 0)
tatry_easy.add_edge(dolina_pan_z, przel_krzyzne, 105, 0)
tatry_easy.add_edge(czarny_staw_gasienicowy_n, pttk_hala_gasienicowa, 30, 0)
tatry_easy.add_edge(pttk_hala_gasienicowa, przel_miedzy_kopami, 25, 0)
tatry_easy.add_edge(pttk_hala_gasienicowa, szalasiska, 30, 0)
tatry_easy.add_edge(jaszczurowka, wielki_kopiec, 70, 0)
tatry_easy.add_edge(wielki_kopiec, olczysta_pol, 60, 0)
tatry_easy.add_edge(olczysta_pol, jaszczurowka_2, 70, 0)
tatry_easy.add_edge(olczysta_pol, nosalowa_przel, 25, 0)
tatry_easy.add_edge(nosalowa_przel, parking_kuznice, 50, 0)
tatry_easy.add_edge(nosalowa_przel, kuznice, 30, 0)
tatry_easy.add_edge(parking_kuznice, kuznice, 15, 0)
tatry_easy.add_edge(parking_kuznice, dolina_bialego, 30, 0)
tatry_easy.add_edge(kuznice, przel_miedzy_kopami, 85, 0)
tatry_easy.add_edge(kuznice, myslenickie_turnie, 60, 0)
tatry_easy.add_edge(kuznice, pttk_kalatowki, 35, 0)
tatry_easy.add_edge(kuznice, pttk_hala_kondratowa, 80, 0)
tatry_easy.add_edge(myslenickie_turnie, kasprowy, 105, 0)
tatry_easy.add_edge(szalasiska, liliowe, 60, 0)
tatry_easy.add_edge(szalasiska, kasprowy, 55, 0)
tatry_easy.add_edge(kasprowy, przel_pod_kond, 100, 0)
tatry_easy.add_edge(przel_pod_kond, kondracka, 20, 0)
tatry_easy.add_edge(przel_pod_kond, pttk_hala_kondratowa, 80, 0)
tatry_easy.add_edge(kondracka, przel_kond, 45, 0)
tatry_easy.add_edge(kondracka, malolaczniak, 30, 0)
tatry_easy.add_edge(przel_kond, pttk_hala_kondratowa, 75, 0)
tatry_easy.add_edge(przel_kond, wyznia_przel_kond, 15, 0)
tatry_easy.add_edge(przel_kond, wielka_polana, 110, 0)
tatry_easy.add_edge(pttk_hala_kondratowa, pttk_kalatowki, 50, 0)
tatry_easy.add_edge(wyznia_przel_kond, giewont, 15, 0)
tatry_easy.add_edge(wyznia_przel_kond, przel_w_grzyb, 90, 0)
tatry_easy.add_edge(przel_w_grzyb, polana_strazyska, 50, 0)
tatry_easy.add_edge(przel_w_grzyb, wielka_polana, 30, 0)
tatry_easy.add_edge(polana_strazyska, siklawica, 15, 0)
tatry_easy.add_edge(polana_strazyska, czerwona_przel, 50, 0)
tatry_easy.add_edge(polana_strazyska, dolina_stazyska, 40, 0)
tatry_easy.add_edge(czerwona_przel, sarnia, 10, 0)
tatry_easy.add_edge(czerwona_przel, polana_bialego, 15, 0)
tatry_easy.add_edge(polana_bialego, pttk_kalatowki, 70, 0)
tatry_easy.add_edge(polana_bialego, dolina_bialego, 70, 0)
tatry_easy.add_edge(dolina_bialego, droga_pod_reglami, 20, 0)
tatry_easy.add_edge(droga_pod_reglami, dziura, 25, 0)
tatry_easy.add_edge(droga_pod_reglami, dolina_stazyska, 25, 0)
tatry_easy.add_edge(dolina_stazyska, dolina_za_bram, 40, 0)
tatry_easy.add_edge(dolina_za_bram, dolina_malej, 40, 0)
tatry_easy.add_edge(dolina_malej, nedzowka, 25, 0)
tatry_easy.add_edge(dolina_malej, rapasiowa_turnia, 35, 0)
tatry_easy.add_edge(nedzowka, kiry, 20, 0)
tatry_easy.add_edge(nedzowka, przyslop_miet, 90, 0)
tatry_easy.add_edge(kiry, cudakowa_pol, 20, 0)
tatry_easy.add_edge(rapasiowa_turnia, wielka_polana, 20, 0)
tatry_easy.add_edge(rapasiowa_turnia, przyslop_miet, 25, 0)
tatry_easy.add_edge(wielka_polana, przyslop_miet, 15, 0)
tatry_easy.add_edge(przyslop_miet, malolaczniak, 180, 0)
tatry_easy.add_edge(przyslop_miet, cudakowa_pol, 50, 0)
tatry_easy.add_edge(cudakowa_pol, chuda_przel, 165, 0)
tatry_easy.add_edge(cudakowa_pol, brama_krasz, 15, 0)
tatry_easy.add_edge(cudakowa_pol, niznia_kominiarska, 40, 0)
tatry_easy.add_edge(malolaczniak, ciemniak, 40, 0)
tatry_easy.add_edge(ciemniak, chuda_przel, 40, 0)
tatry_easy.add_edge(chuda_przel, pttk_ornaczanska, 90, 0)
tatry_easy.add_edge(brama_krasz, wyznia_pisana, 15, 0)
tatry_easy.add_edge(brama_krasz, polana_na_stolach, 70, 0)
tatry_easy.add_edge(wyznia_pisana, pttk_ornaczanska, 30, 0)
tatry_easy.add_edge(pttk_ornaczanska, smreczynski_staw, 30, 0)
tatry_easy.add_edge(pttk_ornaczanska, iwanicka_przel, 70, 0)
tatry_easy.add_edge(dolina_lejowa, kiry, 25, 0)
tatry_easy.add_edge(dolina_lejowa, niznia_kominiarska, 70, 0)
tatry_easy.add_edge(dolina_lejowa, miedzy_sciany, 80, 0)
tatry_easy.add_edge(miedzy_sciany, lesniczowka_chocho, 20, 0)
tatry_easy.add_edge(lesniczowka_chocho, iwanicka_przel, 90, 0)
tatry_easy.add_edge(lesniczowka_chocho, siwa_przel, 150, 0)
tatry_easy.add_edge(lesniczowka_chocho, polana_trzydniowka, 10, 0)
tatry_easy.add_edge(iwanicka_przel, ornak, 60, 0)
tatry_easy.add_edge(ornak, siwa_przel, 60, 0)
tatry_easy.add_edge(siwa_przel, siwy_zwrotnik, 20, 0)
tatry_easy.add_edge(siwy_zwrotnik, blyszcz, 40, 0)
tatry_easy.add_edge(blyszcz, pysznianska_przel, 45, 0)
tatry_easy.add_edge(siwy_zwrotnik, starobocianski, 30, 0)
tatry_easy.add_edge(starobocianski, konczysty, 40, 0)
tatry_easy.add_edge(konczysty, trzydniowianski, 50, 0)
tatry_easy.add_edge(konczysty, jarzabczy_wierch, 40, 0)
tatry_easy.add_edge(trzydniowianski, polana_trzydniowka, 120, 0)
tatry_easy.add_edge(trzydniowianski, dolina_jarzabcza, 80, 0)
tatry_easy.add_edge(polana_trzydniowka, chocholowska, 20, 0)
tatry_easy.add_edge(chocholowska, dolina_jarzabcza, 40, 0)
tatry_easy.add_edge(chocholowska, grzes, 40, 0)
tatry_easy.add_edge(chocholowska, dolina_wyznia, 135, 0)
tatry_easy.add_edge(grzes, rakon, 60, 0)
tatry_easy.add_edge(rakon, dolina_wyznia, 10, 0)
tatry_easy.add_edge(dolina_wyznia, wolowiec, 25, 0)
tatry_easy.add_edge(wolowiec, jarzabczy_wierch, 120, 0)
tatry_easy.add_edge(parking_kuznice, jaszczurowka, 25, 0)
tatry_easy.add_edge(jaszczurowka, jaszczurowka_2, 25, 0)
tatry_easy.add_edge(jaszczurowka_2, brzeziny_les, 30, 0)

tatry_medium = Graph()
tatry_medium.graph_dict = tatry_easy.graph_dict

tatry_medium.add_edge(dolina_za_mnichem, szpiglasowa_przel, 60, 1)
tatry_medium.add_edge(szpiglasowa_przel, szpiglasowy_wierch, 15, 1)
tatry_medium.add_edge(szpiglasowa_przel, niznie_solnisko, 90, 1)
tatry_medium.add_edge(niznie_solnisko, kozia_przel, 70, 1)
tatry_medium.add_edge(niznie_solnisko, kozi_wierch, 90, 1)
tatry_medium.add_edge(niznie_solnisko, zawrat, 60, 1)
tatry_medium.add_edge(skrajny_granat, czarny_staw_gasienicowy_z, 110, 1)
tatry_medium.add_edge(zadni_granat, zamarzly_staw_z, 75, 1)
tatry_medium.add_edge(przel_nad_buczy, zamarzly_staw_z, 75, 1)
tatry_medium.add_edge(kozia_przel, zamarzly_staw_z, 40, 1)
tatry_medium.add_edge(zawrat, zamarzly_staw_n, 70, 1)
tatry_medium.add_edge(zamarzly_staw_n, zamarzly_staw_z, 15, 1)
tatry_medium.add_edge(zamarzly_staw_n, czarny_staw_gasienicowy_z, 20, 1)
tatry_medium.add_edge(czarny_staw_gasienicowy_z, czarny_staw_gasienicowy_n, 10, 1)
tatry_medium.add_edge(szalasiska, zielony_staw, 30, 1)
tatry_medium.add_edge(zielony_staw, karb, 30, 1)
tatry_medium.add_edge(karb, koscielec, 50, 1)
tatry_medium.add_edge(karb, czarny_staw_gasienicowy_n, 40, 1)
tatry_medium.add_edge(swinicka_przel, liliowe, 30, 1)
tatry_medium.add_edge(swinicka_przel, swinica, 45, 1)
tatry_medium.add_edge(liliowe, kasprowy, 20, 1)
tatry_medium.add_edge(wyznia_pisana, mylna, 50, 1)
tatry_medium.add_edge(wyznia_pisana, smocza, 50, 1)

tatry_hard = Graph()
tatry_hard.graph_dict = tatry_medium.graph_dict

tatry_hard.add_edge(czarny_staw, rysy, 180, 2)
tatry_hard.add_edge(czarny_staw, kazalnica, 120, 2)
tatry_hard.add_edge(kazalnica, przel_pod_chlopkiem, 30, 2)
tatry_hard.add_edge(przel_krzyzne, skrajny_granat, 125, 2)
tatry_hard.add_edge(skrajny_granat, zadni_granat, 15, 2)
tatry_hard.add_edge(zadni_granat, przel_nad_buczy, 35, 2)
tatry_hard.add_edge(przel_nad_buczy, kozi_wierch, 45, 2)
tatry_hard.graph_dict[kozia_przel.value].add_edge(kozi_wierch.value, 90, 2)
tatry_hard.graph_dict[zawrat.value].add_edge(kozia_przel.value, 80, 2)
tatry_hard.add_edge(zawrat, swinica, 50, 2)
tatry_hard.add_edge(zielony_staw, swinicka_przel, 55, 2)